//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teste.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class slots
    {
        public int idSlot { get; set; }
        public Nullable<int> dia { get; set; }
        public string horarioInicial { get; set; }
        public string horarioFinal { get; set; }
        public int tipoEvento_idTipoEvento { get; set; }
        public int auditorios_idAuditorio { get; set; }
        public int eventos_idEvento { get; set; }
    }
}
