//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administrativo.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class xtreme_palestraEntities : DbContext
    {
        public xtreme_palestraEntities()
            : base("name=xtreme_palestraEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<auditorios> auditorios { get; set; }
        public DbSet<contatoEmpresa> contatoEmpresa { get; set; }
        public DbSet<dados> dados { get; set; }
        public DbSet<empresas> empresas { get; set; }
        public DbSet<eventos> eventos { get; set; }
        public DbSet<funcoes> funcoes { get; set; }
        public DbSet<pessoas> pessoas { get; set; }
        public DbSet<relFuncaoEventoPessoa> relFuncaoEventoPessoa { get; set; }
        public DbSet<slots> slots { get; set; }
        public DbSet<tipoEvento> tipoEvento { get; set; }
    }
}
