//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administrativo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class eventos
    {
        public int idEvento { get; set; }
        public Nullable<int> ordemSite { get; set; }
        public string tituloPt { get; set; }
        public string tituloEn { get; set; }
        public string tituloEs { get; set; }
        public string sinopsePt { get; set; }
        public string sinopseEn { get; set; }
        public string sinopseEs { get; set; }
        public int empresas_idEmpresa { get; set; }
    }
}
